### ISSUE TITLE
Fatal Error PHP 7.0 failed to require git template

### ISSUE THREAD

**Issue by vpassapera** [phpmetrics/PhpMetrics#286] opened 2017-05-10 02:01 UTC
Hi,

I've installed PhpMetrics 2.2.0 as phar archive.
```
        "tools": {
            "phpmd-extension": {
                "url": "https://github.com/mi-schi/phpmd-extension/releases/download/stable/phpmd-extension.phar",
                "only-dev": true,
                "force-replace": true
            },
            "phpmetrics": {
                "url": "https://github.com/phpmetrics/PhpMetrics/releases/download/v2.2.0/phpmetrics.phar",
                "only-dev": true,
                "force-replace": true
            }
        }
```

When I run this command:

```
/vagrant/bin/phpmetrics.phar --git --junit=build/phpunit/logs/junit.xml --report-html=build/phpmetrics/html --report-violations=build/phpmetrics/logs/violations.xml src

```

I get this output:

```
...................................Executing system analyzes...

LOC
    Lines of code                               1927
    Logical lines of code                       874
    Comment lines of code                       1053
    Average volume                              33.5
    Average comment weight                      12.41
    Average intelligent content                 12.41
    Logical lines of code by class              25
    Logical lines of code by method             9

Object oriented programming
    Classes                                     35
    Interface                                   0
    Methods                                     97
    Methods by class                            2.77
    Lack of cohesion of methods                 0.33
    Average afferent coupling                   0.37
    Average efferent coupling                   2
    Average instability                         0.22

Complexity
    Average Cyclomatic complexity by class      0.37
    Average Relative system complexity          14.28
    Average Difficulty                          0.85
    
Bugs
    Average bugs by class                       0.01
    Average defects by class (Kan)              0.06

Violations
    Critical                                    0
    Error                                       0
    Warning                                     0
    Information                                 1

Top 10 committed files
    10    RoboFile.php
    4    src/AppBundle/Controller/DefaultController.php
    4    src/AppBundle/Controller/ArtifactController.php
    4    src/AppBundle/Response/Collection/ArtifactCollectionResponse.php
    4    src/AppBundle/Repository/ArtifactRepository.php
    4    src/AppBundle/Response/BranchResponse.php
    4    src/AppBundle/Entity/Branch.php
    3    src/AppBundle/CommandBus/UpdateArtifactCommand.php
    3    src/AppBundle/Entity/Artifact.php
    3    src/AppBundle/Validator/Constraints/IsSemverValidator.php
Unit testing
    Number of unit tests
    Classes called by tests                     13
    Classes called by tests (percent)           37.14 %

PHP Warning:  require(phar:///vagrant/vendor/tm/tooly-composer-script/bin/phpmetrics.phar/src/Hal/Report/Html/template/git.php): failed to open stream: phar error: "src/Hal/Report/Html/template/git.php" is not a file in phar "/vagrant/vendor/tm/tooly-composer-script/bin/php
metrics.phar" in phar:///vagrant/vendor/tm/tooly-composer-script/bin/phpmetrics.phar/src/Hal/Report/Html/Reporter.php on line 124
PHP Stack trace:
PHP   1. {main}() /vagrant/vendor/tm/tooly-composer-script/bin/phpmetrics.phar:0
PHP   2. Hal\Application\Application->run() /vagrant/vendor/tm/tooly-composer-script/bin/phpmetrics.phar:16
PHP   3. Hal\Report\Html\Reporter->generate() phar:///vagrant/vendor/tm/tooly-composer-script/bin/phpmetrics.phar/src/Hal/Application/Application.php:70
PHP   4. Hal\Report\Html\Reporter->renderPage() phar:///vagrant/vendor/tm/tooly-composer-script/bin/phpmetrics.phar/src/Hal/Report/Html/Reporter.php:84
PHP Fatal error:  require(): Failed opening required 'phar:///vagrant/vendor/tm/tooly-composer-script/bin/phpmetrics.phar/src/Hal/Report/Html/template/git.php' (include_path='.:/usr/share/pear:/usr/share/php') in phar:///vagrant/vendor/tm/tooly-composer-script/bin/phpmetric
s.phar/src/Hal/Report/Html/Reporter.php on line 124
PHP Stack trace:
PHP   1. {main}() /vagrant/vendor/tm/tooly-composer-script/bin/phpmetrics.phar:0
PHP   2. Hal\Application\Application->run() /vagrant/vendor/tm/tooly-composer-script/bin/phpmetrics.phar:16
PHP   3. Hal\Report\Html\Reporter->generate() phar:///vagrant/vendor/tm/tooly-composer-script/bin/phpmetrics.phar/src/Hal/Application/Application.php:70
PHP   4. Hal\Report\Html\Reporter->renderPage() phar:///vagrant/vendor/tm/tooly-composer-script/bin/phpmetrics.phar/src/Hal/Report/Html/Reporter.php:84
 [Exec]  Exit code 255  Time 54.038s
```

Expected:

Runs and generates reports.

Specifying an absolute path to git bin does not work.
IF i remove the `--git` line it works fine, but does not generate git reports.

**Comment by niconoe-** [comment] 2017-09-13 11:52
Tested using git option with and without defining git binary path, on local environment and inside a docker-container, with the direct sources and the phar archive... All of these work as expected.

Maybe your problem is from your vagrant?

Have you tried to check that the `git` command is accessible for all users in your vagrant?
Thanks.

**Comment by vpassapera** [comment] 2017-09-13 17:02
It is.

**Comment by niconoe-** [comment] 2017-09-13 18:00
I finally find a way to reproduce.

Effectivelly, it seems that the phar archive to download miss the file "git.php".

Steps to reproduce
--------------------------

1) Get into a new empty folder
2) Create a `Dockerfile` containing the following (basic docker-image containing phpmetrics and git):
```
FROM php:7.1-fpm-alpine

RUN PHP_METRICS_VERSION=$(curl -Ls https://raw.githubusercontent.com/phpmetrics/PhpMetrics/master/.semver | grep -Eo ':(major|minor|patch): *[0-9]+' | grep -Eo '[0-9]+' | tr '\n' '.' | sed 's/.$//') \
    && curl -Ls https://github.com/phpmetrics/PhpMetrics/releases/download/v$PHP_METRICS_VERSION/phpmetrics.phar > /usr/local/bin/phpmetrics \
    && chmod +x /usr/local/bin/phpmetrics \
    && apk add --no-cache --virtual .tools git openssh \
    && rm -rf /var/cache/apk/* /var/tmp/* /tmp/*

VOLUME ["/data"]
WORKDIR /data/www

ENTRYPOINT ["phpmetrics"]
CMD ["--version"]
```
3) Locally build this image with a tag, like:
`$> docker build -t test_phpmetrics .`

4) Go into the project you want to run PhpMetrics and try to run the phpmetrics command with this local image, with:
`$> docker run --rm --volume $(pwd):/data/www test_phpmetrics --git --report-html=report <your_src_root>`

5) Read the error...

**Comment by FractalizeR** [comment] 2017-09-14 14:56
I think we should rebuild this phar on every release for it to contain all the latest code.

**Comment by niconoe-** [comment] 2017-09-18 11:18
I'm planning a release 2.3.0 with some improvements already merged into `master`, but I'll try to add some other stuff. Maybe this will be fixed by the new generated phar of the new release...

**Comment by niconoe-** [comment] 2017-09-19 17:35
When building the phar archive, all of these source files are ignored:

```
Building phar
# src/Hal/Report/Html/template/git.php
# tests/binary/BinTest.php
# tests/binary/PharTest.php
# tests/binary/ReportTest.php
# tests/binary/examples/2/file1.php
# tests/binary/examples/1/file1.php
# tests/Component/Issuer/IssuerTest.php
# tests/Component/Tree/GraphDeduplicatedTest.php
# tests/Component/Tree/GraphTest.php
# tests/Component/Tree/HashMapTest.php
# tests/Component/Tree/NodeTest.php
# tests/Component/Tree/Operator/CycleDetectorTest.php
# tests/Component/Tree/Operator/SizeOfTreeTest.php
# tests/Metric/examples/annotations1.php
# tests/Metric/examples/cyclomatic1.php
# tests/Metric/examples/cyclomatic_anon.php
# tests/Metric/examples/externals1.php
# tests/Metric/examples/halstead1.php
# tests/Metric/examples/halstead2.php
# tests/Metric/examples/halstead3.php
# tests/Metric/examples/halstead4.php
# tests/Metric/examples/kan1.php
# tests/Metric/examples/lcom1.php
# tests/Metric/examples/loc1.php
# tests/Metric/examples/nbmethods1.php
# tests/Metric/examples/systemcomplexity1.php
# tests/Metric/System/UnitTesting/UnitTestingTest.php
# tests/Metric/System/UnitTesting/examples/1.php
# tests/Metric/System/UnitTesting/examples/2.php
# tests/Metric/System/UnitTesting/examples/3.php
# tests/Metric/Class_/ClassEnumVisitorTest.php
# tests/Metric/Class_/Component/MaintainabilityIndexVisitorTest.php
# tests/Metric/Class_/Coupling/ExternalsVisitorTest.php
# tests/Metric/Class_/Text/HalsteadVisitorTest.php
# tests/Metric/Class_/Text/LengthVisitorTest.php
# tests/Metric/Class_/Complexity/CyclomaticComplexityVisitorTest.php
# tests/Metric/Class_/Complexity/KanDefectVisitorTest.php
# tests/Metric/Class_/Complexity/SystemComplexityVisitorTest.php
# tests/Metric/Class_/Structural/LcomVisitorTest.php
# tests/Metric/Helper/RoleOfMethodDetectorTest.php
# tests/Application/Config/ParserTest.php
# tests/Application/Config/File/ConfigFileReaderTest.php
# tests/Violation/examples/godobject.php
# tests/Violation/examples/singleton.php
# tests/Violation/Class_/BlobTest.php
# src/Hal/Report/Html/template/images/logo-git.png
```

Of course, the Tests files are ignored, but the first of the list explain why there is trouble with the phar archive and the `--git` option...

This is due to the regular expression that filters the files to include in the phar using the pattern `.git` instead of `\.git`. So, all file names containing "*git" are ignored...

I'm fixing this in a future PR.

**Closed** 2017-09-20 05:20 UTC
Labels: bug
