### ISSUE TITLE
composer dependencies are not being checked properly

### ISSUE THREAD

**Issue by douglasjam** [phpmetrics/PhpMetrics#450] opened 2021-02-11 16:34 UTC
After running the report and looking for outdated libraries, I see it's not optimal yet

### when minor part not mentioned, perhaps it should not complain about it
aws/aws-sdk-php
required ^3.173
latest: 3.173.6
This package should be updated.

### not working properly with 2 digits
symfony/flex
required ^1.12
latest: 1.9.3
This package should be updated.

### my environment
PHPMetrics v2.7.4
PHP 8.0.1
Composer 2.0.9

**Comment by Halleck45** [comment] 2021-06-06 20:52
Hello,

PhpMetrics uses the PHP function [version_compare](https://www.php.net/version_compare)

I cannot reproduce the issue. Do you have any idea (code is [here]https://github.com/phpmetrics/PhpMetrics/blob/master/src/Hal/Metric/System/Packages/Composer/Composer.php#L50) ?

Thanks

**Comment by niconoe-** [comment] 2023-09-19 06:41
Fixed on 3.0.0-rc4

**Closed by niconoe-** 2023-09-19 06:41 UTC
Labels: Cannot reproduce
