### ISSUE TITLE
Unable to scan files that are not ".php" despite manually setting --exclusions

### ISSUE THREAD

**Issue by markgifford** [phpmetrics/PhpMetrics#452] opened 2021-02-11 18:06 UTC
# Bug report

PhpMetrics v2.7.4 <http://www.phpmetrics.org>
by Jean-François Lépine <https://twitter.com/Halleck45>

I'd like to scan .inc, .theme, .module files as well as .php because I'm using this tool on a Drupal project. All those filetypes tend to be PHP. 

When I pass in e.g. `--extensions=inc`, or `--extensions=theme,inc` or `--extensions="theme,inc"`, the result is the same: 0 files scanned, even though my target directory has many of those types of files. If I run the command without --extensions, the result is that it scans all the .php files, as expected.

I've also temporarily amended config.json:

```
    "extensions": [
        "php",
        "php8",
        "inc",
        "module",
        "theme"
    ],
```

But with that, I get the same result: .php files are the only ones scanned.

Any ideas?

**Comment by Halleck45** [comment] 2021-06-06 19:57
Hi,

I cannot reproduce:

```bash
mkdir /tmp/try
echo "<?php class A {}" > /tmp/try/foo.php8
echo "<?php class B {}" > /tmp/try/foo.inc
```

Then

```bash
./bin/phpmetrics /tmp/try|grep Classes
```
>    Classes                                     0

Now we use the `extensions` options :

```bash
./bin/phpmetrics --extensions=php8,foo,inc /tmp/try|grep Classes
```

>   Classes                                     2

As you can see, all classes are found.

Can you confirm that aliven that I cannot reproduce for the moment, I close this issue. Feel free to open it again :)

**Closed by Halleck45** 2021-06-06 19:57 UTC
