### ISSUE TITLE
Allowed memory size of XXX bytes exhausted

### ISSUE THREAD

**Issue by infectormp** [phpmetrics/PhpMetrics#188] opened 2016-02-28 08:51 UTC
Get some memory size error when scan code. I try it with different memory_limit.

Allowed memory size of 268435456 bytes exhausted (tried to allocate 528384 bytes) in phar:///usr/local/bin/phpmetrics/src/Hal/Component/Token/TokenCollection.php on line 118

Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in phar:///usr/local/bin/phpmetrics/src/Hal/Component/Token/TokenCollectionCompatibility.php on line 56

Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in phar:///usr/local/bin/phpmetrics/src/Hal/Component/Token/TokenCollectionCompatibility.php on line 34

Want suggest add option to ignore files by size ```--max-size```

**Comment by YuraLukashik** [comment] 2016-02-28 14:19
@infectormp it's the very huge amount of memory, so i don't think the reason is a huge size of file. May be there is a bug with recursion or something like it.
Could you provide the file causing the failure?
Could you provide your full terminal output?

**Comment by infectormp** [comment] 2016-02-28 16:17
this is full output
98/184 [==============>-------------]  53%PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in phar:///usr/local/bin/phpmetrics/src/Hal/Component/Token/TokenCollectionCompatibility.php on line 34

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in phar:///usr/local/bin/phpmetrics/src/Hal/Component/Token/TokenCollectionCompatibility.php on line 34

Look like tcpdf_5.0.002\fonts cause this error. But when i try check files one by one all work fine.

**Comment by YuraLukashik** [comment] 2016-02-28 19:31
@infectormp which php version do you use? try php 7.0.0, it might provide us some useful info

**Comment by Halleck45** [comment] 2016-02-29 06:49
PhpMetrics use the `token_get_all()` native PHP function to parse code. We cannot change the way this function parse code and use memory. But we can try to optimize the PhpMetrics's code...

Meanwhile, you can:

+ avoid to parse tcpdf files (tcpdf is a library, if you want to get metrics about your code, avoid to parse vendors and libraries)
+ increase your [memory_limit](http://php.net/manual/en/ini.core.php#ini.memory-limit).

**Comment by infectormp** [comment] 2016-03-01 08:14
@YuraLukashik i try PHP7 with same result. 
@Halleck45 i increase memory_limit to 512M.

**Comment by infectormp** [comment] 2016-03-01 09:04
When i test [PhpCodeFixer](https://github.com/wapmorgan/PhpCodeFixer) i get similar error. It was infinite loop during file scanning.
Current error look very similar because does not appear to sing file.

**Comment by YuraLukashik** [comment] 2016-03-02 09:41
@infectormp I suggest you to debug it with xdebug, ping me in skype(YuraLukashik) and I'll help you :)

**Comment by infectormp** [comment] 2016-03-02 11:31
additional info with xdebug
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in phar:///usr/local/bin/phpmetrics/src/Hal/Component/Token/TokenCollectionCompatibility.php on line 34
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpmetrics:0
PHP   2. Symfony\Component\Console\Application->run() /usr/local/bin/phpmetrics:17
PHP   3. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Application.php:123
PHP   4. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Application.php:192
PHP   5. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Application.php:841
PHP   6. Hal\Application\Command\RunMetricsCommand->execute() phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Command/Command.php:259
PHP   7. Hal\Application\Command\Job\Queue->execute() phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/RunMetricsCommand.php:125
PHP   8. Hal\Application\Command\Job\DoAnalyze->execute() phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/Queue.php:51
PHP   9. Hal\Application\Command\Job\Analyze\FileAnalyzer->execute() phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/DoAnalyze.php:132
PHP  10. Hal\Metrics\Complexity\Text\Length\Loc->calculate() phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/Analyze/FileAnalyzer.php:124
PHP  11. Hal\Component\Token\Tokenizer->tokenize() phar:///usr/local/bin/phpmetrics/src/Hal/Metrics/Complexity/Text/Length/Loc.php:47
PHP  12. Hal\Component\Token\TokenCollection->__construct() phar:///usr/local/bin/phpmetrics/src/Hal/Component/Token/Tokenizer.php:45
PHP  13. Hal\Component\Token\TokenCollectionCompatibility->decorate() phar:///usr/local/bin/phpmetrics/src/Hal/Component/Token/TokenCollection.php:38

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in phar:///usr/local/bin/phpmetrics/src/Hal/Component/Token/TokenCollectionCompatibility.php on line 34

Call Stack:
    0.0001     220992   1. {main}() /usr/local/bin/phpmetrics:0
    0.0323    2784496   2. Symfony\Component\Console\Application->run() /usr/local/bin/phpmetrics:17
    0.0350    3138416   3. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Application.php:123
    0.0351    3139064   4. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Application.php:192
    0.0352    3139640   5. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Application.php:841
    0.0355    3145248   6. Hal\Application\Command\RunMetricsCommand->execute() phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Command/Command.php:259
    0.0461    4305392   7. Hal\Application\Command\Job\Queue->execute() phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/RunMetricsCommand.php:125
    0.0461    4306320   8. Hal\Application\Command\Job\DoAnalyze->execute() phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/Queue.php:51
   85.7652  387506016   9. Hal\Application\Command\Job\Analyze\FileAnalyzer->execute() phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/DoAnalyze.php:132
   88.7531  487496912  10. Hal\Metrics\Complexity\Text\Length\Loc->calculate() phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/Analyze/FileAnalyzer.php:124
   88.7531  487497056  11. Hal\Component\Token\Tokenizer->tokenize() phar:///usr/local/bin/phpmetrics/src/Hal/Metrics/Complexity/Text/Length/Loc.php:47
   88.7531  487497184  12. Hal\Component\Token\TokenCollection->__construct() phar:///usr/local/bin/phpmetrics/src/Hal/Component/Token/Tokenizer.php:45
   89.4853  520740536  13. Hal\Component\Token\TokenCollectionCompatibility->decorate() phar:///usr/local/bin/phpmetrics/src/Hal/Component/Token/TokenCollection.php:38

**Comment by pavarnos** [comment] 2016-03-02 21:29
same. I doubled the ram to 1024M (for a project with 1400 files) and it completed ok. but there were (possibly unrelated) javascript problems with the generated output. Will post a separate bug report

**Comment by theofidry** [comment] 2016-03-06 18:47
Maybe a little profiling could help: [blackfire profile](https://blackfire.io/profiles/0fb5dace-0712-43c6-b39d-1bd567b58c95/graph).

FYI once installed it just requires to do `blackfire run phpmetrics ...` and here you go.

**Comment by Halleck45** [comment] 2016-03-20 21:21
I don't know how to help you on this issue...

The main problem with RAM used by PhpMetrics concerns the `token_get_all()` function... I've tried to optimize the use of this function, but without success (I've introduced bugs).

Sadly, today my only recommendation is to increase the RAM :/

@pavarnos , do not hesitate to open new issue.

I close this issue. Feel free to reopen it if you think that is useful.

**Comment by pavarnos** [comment] 2016-03-22 20:56
I've spent a bit of time reading the code (which it beautiful btw!)

src/Hal/Application/Command/RunMetricsCommand.php does
```php
        gc_disable();
        $queue->execute($collection, $aggregatedResults);
        gc_enable();
```

Is this for performance?
I'm not sure what you have tried... but i wonder if this is the cause of the large memory consumption. Blackfire may tell you in detail...

One possible (naive) solution is to make it optional. Eg just before the end of QueueFactory::factory() decorate the queue, 
```php
   if ($this->config->fastModeSelected()) {
        $queue = new FastQueue();
   } else {
        $queue = new Queue();
   }
```

where 
```php
class FastQueue extends Queue {
    public function execute(ResultCollection $collection, ResultCollection $aggregatedResults) {
        foreach($this->jobs as $job) {
            gc_disable();
            $job->execute($collection, $aggregatedResults);
            gc_collect_cycles();
            gc_enable();
        }
    }
````

**Comment by pavarnos** [comment] 2016-03-22 21:10
A second possibility (again from my naive quick look at the code) is that the Cache is keeping _all_ tokenised files in memory? Does it need to? Could the code be re-arranged to not need a cache but rather have a lazy-loading tokenised file that is discarded when you have finished with it. Or to do the tokenize in DoAnalyze::execute() and pass a TokenCollection everywhere instead of a Tokenizer?

Please forgive me if you have thought of this already...

**Comment by Halleck45** [comment] 2016-03-23 06:52
Hum... using `gc_disable()` and `gc_enable()` really optimize performances. But, indeed, also increase memory usage (garbage collector is disabled).

I'm don't know if adding a `--max-size` or a `--enable-gc` option (as you suggest @pavarnos) is a good idea. PhpMetrics has already lot of options...

According to me, PhpMetrics should not analyze libraries (tcpdf, phpcs...). Vendors should be excluded from analyze. Does the problem exist when you analyze your own code ?

**Comment by infectormp** [comment] 2016-03-23 07:04
Well i not have problem with own code. But my code is small.

But let's look from other side, I am developer of tcpdf and want check my big project, i get a memorry problem. So i need check my project by small pices.

**Comment by pavarnos** [comment] 2016-03-23 07:25
I work on a couple of large projects. One is 2000 files, 170k lines of code (excluding vendors). Its really great to show people the entire project in one hit. When consulting on code quality systems, I like the dot chart and the radar plot as a quick way of getting a feel for how "good" or "bad" a whole project is.

What do you think of the second possibility? (passing a TokenCollection). Would it help? Would you accept a pull request if I made an attempt at it?

**Comment by Halleck45** [comment] 2016-03-23 07:55
@pavarnos yes providing TokenCollection instead of Tokenizer looks a good idea :+1:

**Comment by pavarnos** [comment] 2016-03-23 08:50
working on it now. Running phpmetrics on itself uses 
- 46661632 before refactor
- 34078720 after refactor.

Seems worthwhile so far.

**Comment by Halleck45** [comment] 2016-04-05 05:38
I close this issue: thanks to @pavarnos #208 is merged.

**Closed by Halleck45** 2016-04-05 05:38 UTC
Labels: bug

**Comment by pavarnos** [comment] 2016-04-05 21:13
thanks. do you want the Cache stuff removed now?
