### ISSUE TITLE
~ is not the home directory

### ISSUE THREAD

**Issue by Csardelacal** [phpmetrics/PhpMetrics#215] opened 2016-04-05 10:27 UTC
Hi,

I've installed PhpMetrics 1.8.3 as phar archive. When I run this command:

```
cd ~/NetBeansProjects/myProject
phpmetrics --report-html=~/Desktop/phpmetrics/index.html . --excluded-dirs="lib|tests|templates"
```

The file is written to `/Users/myuser/NetBeansProjects/myProject/~/Desktop/phpmetrics/index.html` which is a rather unexpected behavior. When I add a tilde before a Path I actually expect this to be replaced by the user's home directory.

I would suggest putting `realpath()` around the logic that determines where to write the file.

**Comment by Halleck45** [comment] 2016-04-05 12:38
Hi,

Thank's you for the report !

`realpath()` has no impact about parsing of `~/` expression:

```
php -r "var_dump(realpath('~/'));"
// bool(false)
```

expanding tilde in PHP isn't so easy. You should [detect the tilde, then expand path, and finally replace tilde with the expanded path](http://jonathonhill.net/2013-09-03/tilde-expansion-in-php/).

But we can try. Whant do you think about opening a PR ?

**Comment by Csardelacal** [comment] 2016-04-05 13:14
That should be easy, the code you posted is actually pretty simple (although it probably needs some modifications to prevent it from screwing up). But I'm unfamiliar with the Symfony style of file organization, where would I best put the code?

If it was me I would create a class for translating the paths and then just add a call to it here: https://github.com/phpmetrics/PhpMetrics/blob/master/src/Hal/Application/Command/Job/QueueReportFactory.php#L62
-- Since this is the file that seems to translate all of the paths for the reports.

Correct me if I'm wrong, but if I were to create a class to manipulate files I suppose it would go here: https://github.com/phpmetrics/PhpMetrics/tree/master/src/Hal/Component/File

Assuming these are correct I would gladly open a Pull Request.

**Comment by viruzzo** [comment] 2016-04-27 11:39
This is not a bug in PhpMetrics, nor should it be worked around! Your problem is that the tilde is not at the beginning of the shell parameter, and as such does not get expanded by the shell. Some programs do the expansion themselves, but it means taking up on the shell's responsibility for expanding the parameters.
A quick, correct and portable solution is using `$HOME` instead of `~`.

https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html

**Comment by Csardelacal** [comment] 2016-04-27 14:44
Well, it's obviously not placed at the beginning of the of the parameter, but it is clearly placed at the beginning of the Path. Not expanding the tilde there is not providing any additional functionality.

It's one of those cases where everyone would expect the Tilde to be replaced, it took me a while to notice that I was littering my project directory with this. And I'm pretty confident that the fact that it's not being expanded will surprise most of the users out there.

I'm not aware of many situations where a user would have a directory called `~` in his directory structure and who would be surprised that an application is treating it like the home directory. 

I'm not talking about expanding it everywhere, I'm not talking about expanding it when it's something like `~user/`, which seems to be popular among universities in my experience.

The only case I would be expanding is when it's the first character of the string and is immediately followed by a forward slash.

**Comment by viruzzo** [comment] 2016-04-27 15:12
While I agree that it might be expected, it's the expectation that is incorrect. The problem arises from a misusage of a shell functionality and, however intuitive may it be, "fixing" it is encouraging said misuse, which has no gain over the correct one.

At the same time, implementing it in the application just to match said expectation might lead to other confusing situations where the expansion done by the shell does not match the one done by the application (for example, if not implementing the `~<user>` syntax).

**Comment by Halleck45** [comment] 2017-01-23 17:21
Hi,

@viruzzo I'm agree. Expanding tilde is the reponsability of your shell, not of the program.

I prefer to avoid to expand the tilde, or PhpMetrics will become a "zsh like engine" :p

Maybe we can "patch" the code in order the throw an error if we detect a tilde.

**Comment by Halleck45** [comment] 2017-04-10 11:25
I close this issue. Don not hesitate to reopen it if needed

**Closed by Halleck45** 2017-04-10 11:25 UTC
Labels: enhancement, question
