### ISSUE TITLE
Unable to execute circo -V 2>&1

### ISSUE THREAD

**Issue by Naimadnap** [phpmetrics/PhpMetrics#224] opened 2016-05-23 12:07 UTC
Hi,

I've installed PhpMetrics 1.10 with composer .

When I run this command:
phpmetrics  --report-html=phpmetrics.html --report-xml=phpmetrics.xml --chart-bubbles=chart.svg value=.

```

I get this output:
....
Generating Bubbles chart Report...
PHP Warning:  shell_exec(): Unable to execute 'circo -V 2>&1' in php_tools/vendor/phpmetrics/phpmetrics/src/Hal/Component/Chart/Graphviz.php                                      on line 26

PHP Warning:  proc_open(): fork failed - Cannot allocate memory in php_tools/vendor/symfony/console/Application.php on line 898

  [RuntimeException]
  Graphviz not installed

but:
$ circo -V
circo - graphviz version 2.26.3 (20100126.1600)
```

**Comment by Halleck45** [comment] 2016-09-07 16:16
Hi,

sorry for the delay :/

I cannot reproduce this issue, and v2 does not need Graphviz. Can you test with the [v2 rc](https://github.com/phpmetrics/PhpMetrics/releases/tag/v2.0.0-rc) please ?

**Comment by Halleck45** [comment] 2017-04-10 15:39
This issue is outdated, so I close it. Thanks for your report

**Closed by Halleck45** 2017-04-10 15:39 UTC
Labels: bug, legacy-v1
