### ISSUE TITLE
JavaScript fatal errors

### ISSUE THREAD

**Issue by SmetDenis** [phpmetrics/PhpMetrics#198] opened 2016-03-17 07:44 UTC
Hi,

First of all thanks for tool. Very useful!
Some time ago I had some fatal JS errors appeared (syntax) and I don't know what has happened.

For example 
![image](https://cloud.githubusercontent.com/assets/1118678/13839430/2ed2d704-ec45-11e5-9766-f897e25bef9a.png)

And HTML file
[phpmetrics.zip](https://github.com/phpmetrics/PhpMetrics/files/177421/phpmetrics.zip)

I use last stable v1.8.3 with TeamCity v9.1.6

```sh
mkdir -p build/phpmetrics

phpmetrics ./%source_path% \
    --report-html=build/phpmetrics/report.html \
    --report-xml=build/phpmetrics/report.xml \
    --report-csv=build/phpmetrics/report.csv \
    --report-json=build/phpmetrics/report.json \
    --violations-xml=build/phpmetrics/violations.xml \
    --verbose \
    --no-ansi \
    --symlinks \
    --no-interaction
```

Can you help me please?
Thanks and best regards, Denis.

**Comment by UFOMelkor** [comment] 2016-03-17 08:02
Seems to be a duplicate of #189

v1.8.4 should resolve your issue :-)

**Comment by SmetDenis** [comment] 2016-03-17 08:43
Yea, thanks!

I see you have renamed composer package (vendor name) and I can't get new version.
May be old package should be removed or abandoned ? 

P.S. Just updated to 1.8.5 and  it works fine.

**Comment by Halleck45** [comment] 2016-03-17 08:59
Hum, we have renamed package but we add a `replace` [key in composer.json](https://github.com/phpmetrics/PhpMetrics/blob/master/composer.json#L3).

normally you should be able to install latest version of phpmetrics even with `halleck45/phpmetrics`. oO . I'll check it

**Closed by Halleck45** 2016-03-17 08:59 UTC
Labels: duplicate
